jobs:
  - name: sampleagain-release
    type: release
    steps:
      - IN: testagain-version
      - TASK: managed
        bump: patch
      - IN: sampleagain-manifest
      
        
  - name: sampleagain-manifest
    type: manifest
    steps:
      - IN: testagain-image1
      #- TASK: managed
      - IN: triggertestagain1
      
  - name: sampleagain-manredis
    type: manifest
    steps:
      - IN: test-imageredis
      #- TASK: managed
      - IN: triggertestagain1
      
  - name: sampleagain-ecsdeploy
    type: ecsDeploy
    steps:
      - IN: sampleagain-manredis
      - IN: sampleagain-cluster
      - TASK: managed
        deployMethod: upgrade
