jobs:
  - name: sampletest-release
    type: release
    steps:
      - IN: sampletest-version
      - IN: sampletest-manifest
      - TASK: managed
        bump: minor
        
  - name: sampletest-manifest
    type: manifest
    steps:
      - IN: sampletest-image1
      - TASK: managed
      - IN: triggertestsample1
