jobs:
  - name: sampletest-release
    type: release
    steps:
      - IN: sampletest-version
      - TASK: managed
        bump: minor
      - IN: sampletest-manifest
      
        
  - name: sampletest-manifest
    type: manifest
    steps:
      - IN: sampletest-image1
      - TASK: managed
      - IN: triggertestsample1
      
  - name: sampletest-ecsdeploy
    type: ecsDeploy
    steps:
      - IN: sampletest-manifest
      - TASK: managed
        deployMethod: upgrade
      - IN: sampletest-cluster
      
