jobs:
  - name: test-release
    type: release
    steps:
      - IN: test-version
      - TASK: managed
        bump: patch
      - IN: test-man1
        
  - name: test-man1
    type: manifest
    steps:
      - IN: test-imagerunc1
      - IN: testecs-dopts1
      #- TASK: managed
      - IN: triggertestagain2
      
  - name: test-manredis
    type: manifest
    steps:
      - IN: test-imageredis
      #- TASK: managed
      - IN: triggertestagain1
      
  - name: test-ecsDeploy
    type: ecsDeploy
    steps:
      - IN: test-manredis
      - IN: test-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: testpreviousop-ecsDeploy
    type: ecsDeploy
    steps:
      - IN: test-man1
      - IN: test-ecscluster
